name: Release Obsidian Plugin

on:
  push:
    tags:
      - "*" # 监听所有 tag，例如 1.0.2 或 v1.0.2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build plugin
        run: npm run build

      - name: Extract version from tag
        id: version
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          VERSION=${TAG#v} # 去掉前导 v
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Update manifest.json version
        run: |
          VERSION=${{ steps.version.outputs.version }}
          echo "Setting version to $VERSION"
          jq ".version = \"$VERSION\"" build/manifest.json > build/manifest.json.tmp
          mv build/manifest.json.tmp build/manifest.json

      - name: Create plugin.zip (optional)
        run: |
          cd build
          zip -r ../plugin.zip manifest.json main.js styles.css || true
          cd ..

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/main.js
            build/manifest.json
            plugin.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
